export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const LOAD_TAGS_SUCCESS = 'LOAD_TAGS_SUCCESS';
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';
export const LOAD_PROJECT_SUCCESS = 'LOAD_PROJECT_SUCCESS';

export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';

export const MODIFY_PROJECT_REQUEST = 'MODIFY_PROJECT_REQUEST';
export const MODIFY_PROJECT_SUCCESS = 'MODIFY_PROJECT_SUCCESS';
export const MODIFY_PROJECT_FAILURE = 'MODIFY_PROJECT_FAILURE';

export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';

/* General type for request failures */
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const AUTH_MODAL_OPEN = 'AUTH_MODAL_OPEN';
export const AUTH_MODAL_CLOSE = 'AUTH_MODAL_CLOSE';
